SparkPost/node-sparkpost

.travis.yml
Make sure that Travis CI runs successfully with our current code base. We can customize later (using pre-commit hooks or whatnot if we choose, but this is the right place to start).
=> Issue 12 - Integrate Travis CI

README.md, examples/sendingDomains/create_sendingDomain.js, examples/sendingDomains/get_all_sendingDomains.js, examples/sendingDomains/get_sendingDomain.js, examples/sendingDomains/update_sendingDomain.js, examples/sendingDomains/verify_sendingDomain_default.js, examples/sendingDomains/verify_sendingDomain_dkim_only.js, examples/sendingDomains/verify_sendingDomain_spf_only.js, index.js, lib/sendingDomains.js, test/mocks/request.js, test/mocks/sendingDomains.js, test/spec/sendingDomains.spec.js
This change will add support for the Sending Domains API. Test files have been added at 100% coverage.
=> Issue 9 - Sending Domains API implementation

README.md, examples/transmission/mime_parts.js, examples/transmission/send_transmission_all_fields.js, lib/transmission.js, test/spec/transmissions.spec.js
creating pull request for code review
=> removed defaulting open/click tracking to true

lib/sendingDomains.js, test/spec/sendingDomains.spec.js
=> ISSUE-38 Updated Sending Domains unit tests. Added error checking.

lib/index.js, lib/suppressionList.js, test/spec/suppressionList.spec.js
=> ISSUE 20: Suppression List SDK

lib/index.js, lib/templates.js, test/spec/templates.spec.js
=> ISSUE 6: Templates SDK

lib/SendGridCompatibility/index.js, lib/index.js, lib/recipientLists.js, lib/transmission.js, package.json, test/spec/recipientLists.spec.js
Here is the start of the Recipient Lists SDK. Right now the toApiFormat function doesn't do anything special. Looking for suggestions on how to handle that. This API takes a big complicated object.
=> Issue 7: Recipient Lists SDK

lib/index.js, lib/webhooks.js, test/spec/webhooks.spec.js
=> Issue 10: Webhooks API

examples/sendingDomains/verify_sendingDomain_default.js, examples/sendingDomains/verify_sendingDomain_dkim_only.js, examples/sendingDomains/verify_sendingDomain_spf_only.js, lib/sendingDomains.js, test/spec/sendingDomains.spec.js
=> ISSUE-42: Modified sendingDomains.vefify and updated the unit tests and examples.

README.md, examples/transmissions/mime_parts.js, examples/transmissions/rfc822.js, examples/transmissions/send_transmission_all_fields.js, examples/transmissions/stored_recipients_inline_content.js, examples/transmissions/stored_recipients_stored_content.js, examples/transmissions/stored_template_send.js, lib/SendGridCompatibility/index.js, lib/transmissions.js, test/spec/SendGridCompatibility/index.spec.js, test/spec/transmissions.spec.js
Fixed a link typo in the README.md and updated Transmissions functions to accept optional parameter. Closes #46
=> Issue 46 Updates to Transmissions library

lib/sparkpost.js, test/spec/sparkpost.spec.js
=> Issue 51: Modify the base object to handle non 2XX status and simplify second callback param

CHANGELOG.md, README.md
=> Created a change log as CHANGELOG.md

examples/sendingDomains/verify_sendingDomain_default.js, examples/sendingDomains/verify_sendingDomain_dkim_only.js, examples/sendingDomains/verify_sendingDomain_spf_only.js, examples/transmissions/send_transmission_all_fields.js, examples/transmissions/stored_recipients_inline_content.js, examples/transmissions/stored_recipients_stored_content.js
Just updating examples to reflect the actual code usage now.
=> Resolving Issue #69 to update examples for newly added toApiFormat

docs/resources/transmissions.md, examples/transmissions/get_transmissions_by_campaign.js, examples/transmissions/get_transmissions_by_template.js, examples/transmissions/mime_parts.js, examples/transmissions/rfc822.js, examples/transmissions/send_transmission_all_fields.js, examples/transmissions/stored_recipients_inline_content.js, examples/transmissions/stored_recipients_stored_content.js, examples/transmissions/stored_template_send.js
Updated transmission.md for new api format. Updated transmission example for new api format. Added two new examples for retrieving transmissions by template and campaign.
Closes #71
Closes #72 
Closes #76
=> Updated transmission docs and examples.

docs/resources/recipientLists.md, examples/recipientLists/update_recipientList.js, lib/recipientLists.js, test/spec/recipientLists.spec.js
=> Added Recipient List Update method, Docs, and Examples

examples/transmissions/send_transmission_all_fields.js
typo user_type instead customer_type
=> correcting send_transmission_all_fields.js example

Gruntfile.js
=> #102: Added a mocha test task to the default grunt task

README.md
Hi. I thought your docs needed a simple "hello world" email example. Hopefully you like this contribution I made. 
thanks,
Jim
=> ReadMe "Hello World" Example

docs/resources/inboundDomains.md, examples/inboundDomains/create_inboundDomain.js, examples/inboundDomains/delete_inboundDomain.js, examples/inboundDomains/find_inboundDomain.js, examples/inboundDomains/get_all_inboundDomains.js, examples/sendingDomains/delete_sendingDomain.js, lib/inboundDomains.js, lib/sparkpost.js, test/spec/inboundDomains.spec.js
Updated docs and examples.
Closes #116
=> Added support for inbound domains.

lib/sparkpost.js, lib/subaccounts.js, test/spec/subaccounts.spec.js
=> Fix missing `subaccounts` property in SparkPost class

Gruntfile.js
=> Make Gruntfile.js cross-platform friendly

package.json, test/spec/sparkpost.spec.js
=> Upgrade request to 2.72.0 and fix affected test

examples/subaccounts/create_subaccount.js, examples/subaccounts/get_all_subaccounts.js, examples/subaccounts/get_subaccount.js, examples/subaccounts/update_subaccount.js
Completing the documentation story for subaccounts so that the readme's examples link won't be broken.
=> add examples of subaccounts resource use

lib/toApiFormat.js, test/spec/toApiFormat.spec.js
=> Preserve array/object structure of API data

.eslintrc, Gruntfile.js, lib/SendGridCompatibility/Email.js, lib/SendGridCompatibility/index.js, lib/inboundDomains.js, lib/messageEvents.js, lib/recipientLists.js, lib/relayWebhooks.js, lib/sendingDomains.js, lib/sparkpost.js, lib/subaccounts.js, lib/suppressionList.js, lib/templates.js, lib/toApiFormat.js, lib/transmissions.js, lib/webhooks.js, package.json, test/spec/inboundDomains.spec.js, test/spec/messageEvents.spec.js, test/spec/recipientLists.spec.js, test/spec/relayWebhooks.spec.js, test/spec/sendingDomains.spec.js, test/spec/subaccounts.spec.js, test/spec/suppressionList.spec.js, test/spec/templates.spec.js, test/spec/transmissions.spec.js, test/spec/webhooks.spec.js
Removed JSHint
Added npm lint script
Switch Grunt to call `npm run lint` until Grunt is removed
Resolved all new linting errors
Closes #155
=> Switched JSHint for ESLint with SparkPost config

.travis.yml, package.json
Removed testing of nodejs versions .10 & .12, added lastest stable, 5, & 6
Closes #153
=> Removed support for nodejs versions .10 & .12

docs/resources/transmissions.md, examples/baseObject/getDomainsList.js, examples/transmissions/get_transmission.js, examples/transmissions/get_transmissions_by_campaign.js, examples/transmissions/get_transmissions_by_template.js, examples/transmissions/mime_parts.js, examples/transmissions/rfc822.js, examples/transmissions/send_transmission_all_fields.js, examples/transmissions/send_transmission_with_bcc.js, examples/transmissions/send_transmission_with_cc.js, examples/transmissions/stored_recipients_inline_content.js, examples/transmissions/stored_recipients_stored_content.js, examples/transmissions/stored_template_send.js, lib/transmissions.js, test/spec/transmissions.spec.js
Refactored tests for promises. Updated examples to be consistent.
=> Updated tests and examples for transmissions

docs/resources/webhooks.md, examples/webhooks/create_webhook.js, examples/webhooks/delete_webhook.js, examples/webhooks/describe_webhook.js, examples/webhooks/getBatchStatus.js, examples/webhooks/getDocumentation.js, examples/webhooks/getSamples.js, examples/webhooks/get_all_webhooks.js, examples/webhooks/update_webhook.js, examples/webhooks/validate_webhook.js, lib/webhooks.js, test/spec/webhooks.spec.js
=> Refactored webhooks library

lib/sparkpost.js
=> Return full body for sparkpost requests

lib/Promise.js, lib/inboundDomains.js, lib/messageEvents.js, lib/recipientLists.js, lib/relayWebhooks.js, lib/sendingDomains.js, lib/sparkpost.js, lib/subaccounts.js, lib/suppressionList.js, lib/templates.js, lib/transmissions.js, lib/webhooks.js
with the wrapper function withCallback, closes #199
=> replace asCallback extension of native Promise prototype

examples/templates/preview.js
=> Added template ID param to preview() call

examples/recipientLists/get.js
fix for [issue #215](https://github.com/SparkPost/node-sparkpost/issues/215)
=> Updated get recipientLists Documentation

package.json
Addresses #222 in response to [this SO question](https://stackoverflow.com/questions/46397018/uncaughtexception-syntaxerror-use-of-const-in-strict-mode-in-sparkpost-modules).
=> Add engines field to package.json

lib/templates.js, package-lock.json, test/spec/templates.spec.js
Fixing #233. Also added the `package-lock.json`
=> Fixing Template Preview draft option

examples/transmissions/send_stored_recipients_stored_content.js
There is an s missing in 'tranmission' on line 29
=> Spelling misstake
