- lib/transmission.js
- test/spec/transmissions.spec.js
I cleaned up the transmissions unit tests so that they are more truly unit tests. I removed some dead code and reorganized a little. I also added some error checking in the transmissions library. This closes #33.
> ISSUE-33 made transmission unit tests more unity

- README.md
The point of using env vars is to hide the API key from the actual code.  However the doc implies you have to set the env var in your code like 
```js
process.env.SPARKPOST_API_KEY='your key';
```
However you should not do that and instead set the env var in something like ~/.profile or ~/.bash_profile
> Fix doc about using process.env.SPARKPOST_API_KEY

- package.json
You currently can't find the SparkPost lib by searching for anything but sparkpost.  I does not come up if you search of email.  This should help give the package and our service more visibility.
> Added keywords for searching in npm

- lib/toApiFormat.js
Make sure to support sending with a stored recipient list or template, while also leaving headers and substitution data alone.
> Resolve issue #82

- lib/sparkpost.js
- package.json
- test/spec/sparkpost.spec.js
- Request's gzip option now defaults to true with caller control
- Bumped nock version to enable gzip support
> #92: Added gzipped response support

- examples/transmissions/stored_template_send.js
I cleaned up our existing template send example. Unless you are doing something fancy with substitution data, people won't be submitting from and subject in the template send.
closes #99
> removes from and subject from transmission stored template send example

- lib/sparkpost.js
- test/spec/sparkpost.spec.js
> Added json flag to base request and tests to check for JSON response

- .jshintrc
- docs/resources/sendingDomains.md
- examples/sendingDomains/delete_sendingDomain.js
- lib/sendingDomains.js
- test/spec/sendingDomains.spec.js
> Added support for deleting a sending domain

- README.md
- docs/resources/relayWebhooks.md
- examples/relayWebhooks/create_relayWebhook.js
- examples/relayWebhooks/delete_relayWebhook.js
- examples/relayWebhooks/find_relayWebhook.js
- examples/relayWebhooks/get_all_relayWebhooks.js
- examples/relayWebhooks/update_relayWebhook.js
- lib/relayWebhooks.js
- lib/sparkpost.js
- test/spec/relayWebhooks.spec.js
Updated examples and docs.
Closes #117
> Added support for Relay Webhooks

- lib/toApiFormat.js
- package.json
- test/spec/toApiFormat.spec.js
- test/spec/transmissions.spec.js
Added tests that showed the problem with `email_rfc822` keys. Refactored toApiFormat.js to use json-pointer, which should allow for more flexible exclusion definition going forward.
> Refactored toApiFormat.js to use json-pointer

- lib/inboundDomains.js
The `json` object needs to contain an object like `{ domain: myDomain }` rather than a plain string domain name.
> Let inboundDomains.create() use a domain name as per the docs

- examples/suppressionList/checkStatus.js
- examples/suppressionList/removeStatus.js
- examples/suppressionList/search_suppressionList.js
- examples/suppressionList/upsert.js
- examples/suppressionList/upsert_bulk.js
- lib/suppressionList.js
Fixes #140
For bulk upserts we needed to send a payload of an object with a recipients key. We were sending an array of recipients.
> Updated bulk suppression list upsert payload.

- package.json
lodash v3 has an issue that causes TypeError: Cannot read property 'prototype' of undefined.
This has been fixed in v4 (lodash/lodash#223).
> Upgrade lodash version to 4

- .jshintrc
- lib/Promise.js
- lib/inboundDomains.js
- lib/messageEvents.js
- lib/recipientLists.js
- lib/relayWebhooks.js
- lib/sendingDomains.js
- lib/sparkpost.js
- lib/subaccounts.js
- lib/suppressionList.js
- lib/templates.js
- lib/transmissions.js
- lib/webhooks.js
- package.json
- test/spec/inboundDomains.spec.js
- test/spec/messageEvents.spec.js
- test/spec/recipientLists.spec.js
- test/spec/relayWebhooks.spec.js
- test/spec/sendingDomains.spec.js
- test/spec/sparkpost.spec.js
- test/spec/subaccounts.spec.js
- test/spec/suppressionList.spec.js
- test/spec/templates.spec.js
- test/spec/transmissions.spec.js
- test/spec/webhooks.spec.js
#107 Used bluebird.js. You can now use a callback or a promise. All the tests still pass but we might want to look at how and what we are testing.
> Implement promise support

- lib/sparkpost.js
- test/spec/sparkpost.spec.js
`options.json` is being set to true for other requests by data being passed into it. `GET` requests need it explicitly set so returned data will be parsed as json.
Also, the current method broke all `POST` and `PUT` requests.
Fixes #111
> Set options.json=true for GET requests

- lib/webhooks.js
- package.json
- test/spec/webhooks.spec.js
Removed `id` from the `webhook` object before passing it on to the request. Added a check to make sure `id` was included and a test.
Added some code cleanup.
Fixes #164
> Updated webhook update method to not send id in request

- docs/resources/subaccounts.md
- examples/subaccounts/create_subaccount.js
- examples/subaccounts/get_all_subaccounts.js
- examples/subaccounts/get_subaccount.js
- examples/subaccounts/list_subaccounts.js
- examples/subaccounts/update_subaccount.js
- lib/subaccounts.js
- test/spec/subaccounts.spec.js
> Refactored subaccounts library

- docs/resources/relayWebhooks.md
- examples/relayWebhooks/create.js
- examples/relayWebhooks/create_relayWebhook.js
- examples/relayWebhooks/delete.js
- examples/relayWebhooks/delete_relayWebhook.js
- examples/relayWebhooks/find_relayWebhook.js
- examples/relayWebhooks/get.js
- examples/relayWebhooks/get_all_relayWebhooks.js
- examples/relayWebhooks/list.js
- examples/relayWebhooks/update.js
- examples/relayWebhooks/update_relayWebhook.js
- lib/relayWebhooks.js
- test/spec/relayWebhooks.spec.js
> Refactored relay webhooks library

- README.md
- docs/async.md
- lib/sparkpost.js
- test/spec/sparkpost.spec.js
> Added setting debug in initialization

- README.md
- lib/sparkpost.js
- test/spec/sparkpost.spec.js
Adds a Node.js version string and an optional "stack identifier" so we can track libs that use node-sparkpost such as nodemailer-sparkpost-transport.
> Add more useful details to the User-Agent header

- CHANGELOG.md
Going forward, we will use [Keep a Changelog](http://keepachangelog.com/en/0.3.0/) as a guide.
Addresses #191
> Refactored the 2.0.0 changelog

- README.md
There does not appear to be any clear documentation to suggest that EU accounts need to configure the client slightly differently in order for it to work.
Without setting the `origin` via the options parameter when initiating a client any requests made with a token from an EU account will return a cryptic 401 error, since requests are going to the US API.
This change adds some explicit mentions of the slightly different configuration needed to get the library working with an EU account.
> ISSUE-234: Document how to configure for the EU API
